
SECTION_DATABASE            = "DATABASE"
PARAMETER_DATABASE_NAME     = "db_name"
PARAMETER_DATABASE_USER     = "db_user"
PARAMETER_DATABASE_PASS     = "db_pass"
PARAMETER_DATABASE_HOST     = "db_host"
PARAMETER_DATABASE_PORT     = "db_port"

SECTION_WORKER              = "WORKER"
PARAMETER_WORKER_INTERVAL   = "interval"

SECTION_LOGS                = "LOGS"
PARAMETER_LOGS_LOGFILE      = "log_file"
PARAMETER_LOGS_MAXSIZE      = "max_size"
PARAMETER_LOGS_LEVEL        = "log_lvl"